# Generated by Django 5.2.7 on 2025-10-11 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Product Name')),
                ('slug', models.SlugField(help_text='A URL-friendly short label for the product.', max_length=255, unique=True)),
                ('brand', models.CharField(default='Unbranded', max_length=100)),
                ('short_description', models.TextField(max_length=500, verbose_name='Short Summary')),
                ('long_description', models.TextField(verbose_name='Detailed Description')),
                ('theme', models.CharField(blank=True, max_length=100, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Retail Price', max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Discount %')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Available Stock')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available Online')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(help_text='e.g., Material, King Size, Use Case', max_length=100)),
                ('feature_value', models.TextField(help_text='e.g., Wood, 5 cm, Educational Game')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_main', models.BooleanField(default=False, verbose_name='Main Display Image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which image is displayed.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('product', 'order')},
            },
        ),
    ]
